### ISSUE TITLE
Update lightning cifar-10 example

### ISSUE THREAD

**Issue by edenlightning** [Lightning-AI/tutorials#249]
### 📚 Documentation

Currently getting the following: 
```
Traceback (most recent call last):
  File "/home/zeus/content/app.py", line 122, in <module>
    trainer.fit(model, cifar10_dm)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_train
    self._run_sanity_check()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1413, in _run_sanity_check
    val_loop.run()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 128, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 226, in _evaluation_step
    output = self.trainer._call_strategy_hook("validation_step", *kwargs.values())
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1765, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 344, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/zeus/content/app.py", line 88, in validation_step
    self.evaluate(batch, "val")
  File "/home/zeus/content/app.py", line 81, in evaluate
    acc = accuracy(preds, y)
TypeError: accuracy() missing 1 required positional argument: 'task'
⚡~/content/
```

cc @borda

**Comment by Borda** [comment]
resolved in #233
